name: Auto Close Unauthorized PRs
on:
  pull_request:
    types: [opened, reopened]

jobs:
  close_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Close PR if not opened by the owner
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          OWNER: "michaelthomasletts"
        run: |
          ACTOR=$(echo "${{ github.actor }}" | tr '[:upper:]' '[:lower:]')
          OWNER_LC=$(echo "$OWNER" | tr '[:upper:]' '[:lower:]')

          if [[ "$ACTOR" != "$OWNER_LC" ]]; then
            gh pr close ${{ github.event.pull_request.number }} --repo "$REPO" --comment "Only the repository owner can open PRs."
          fi
