name: Update README.md

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Runs every hour

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run generate_readme.py
      run: |
        python generate_readme.py

    - name: Set up Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Create new branch
      run: |
        git checkout -b auto-update-readme
        git add README.md
        git commit -m "Auto-update README with new ASCII logo" || echo "No changes to commit"

    - name: Push changes
      run: |
        git push -u origin auto-update-readme

    - name: Create pull request
      id: create_pr
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        base: main
        head: auto-update-readme
        title: "Auto-update README with new ASCII logo"
        body: "This pull request was created automatically by GitHub Actions."

    - name: Merge pull request
      if: steps.create_pr.outputs.pull-request-url != ''
      uses: peter-evans/merge-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        pull-request-url: ${{ steps.create_pr.outputs.pull-request-url }}
        merge-method: squash  # or 'merge', 'rebase'
