name: Update README

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC (adjust as needed)
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # We will use a GitHub token

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install pyfiglet jinja2

      - name: Run Python script to generate README.md
        run: python generate_readme.py

      - name: Commit and push if changed
        env:
          GITHUB_USER: "michaelthomasletts"
          GITHUB_EMAIL: "michaelthomasletts@users.noreply.github.com"
        run: |
          git config --global user.name "$GITHUB_USER"
          git config --global user.email "$GITHUB_EMAIL"
          git add README.md
          git commit -m "Auto-update README with new ASCII logo" || echo "No changes to commit"
          git push