name: Update README

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 11 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
      
      - name: Update branch
        run: |
          git pull

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install git+https://github.com/michaelthomasletts/pepy-chart.git --quiet
      
      - name: Update download stats
        run: |
          python3 packagestats.py
        env:
          PEPY_API_KEY: ${{ secrets.PEPY_API_KEY }}

      - name: Commit and push if image changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "Updating README.md image automatically [skip ci]"
            git pull origin main --rebase
            git push origin main
          else
            echo "No changes to commit"         
          fi            
